#pragma once

#define BAUD_RATE 9600

#define ENCODER_CLK_PIN 2
#define ENCODER_DT_PIN 3
#define ENCODER_SW_PIN 4
#define ENCODER_STEPS_PER_CLICK 4
#define ENCODER_DIRECTION_CC 1
#define ENCODER_DIRECTION_CW -1

#define BUTTON_DEBOUNCE_DURATION 50
#define BUTTON_LONG_PRESS_DURATION 1000

#define SERVO_NEUTAR_ANGLE 90
#define SERVO_MIN_ANGLE 0
#define SERVO_MAX_ANGLE 180
#define SERVO_MIN_US 500
#define SERVO_MAX_US 2500
#define SERVO_NEUTAR_PULSE 1500

#define MS_MODE_MULTIPLER 10

#define TEST_SERVO_PIN 9

#define DISPLAY_ADDRESS 0x3C
#define RENDER_INTERVAL_DURATION 50
#define SCREEN_WIDTH 64
#define SCREEN_HEIGHT 32
#define OLED_RESET -1
